### PR TITLE
Rework yuv2ppm.

### PR DESCRIPTION
**Pull request by andreas-hofmann**
Hi,
I've tweaked the yuv2ppm tool a bit. It uses commandline arguments instead of defines now, adds some yuv conversions taken from Wikipedia, slims down the reads+writes, adds more error handling, plus overall cleanup.

### CODE REVIEW

**Review by marcmerlin — COMMENTED** [review]
thanks for this. I'm a bit swamped right now and can't really review this very soon, but will do my best to do so when things settle down a bit.  
Thank you for your contribution, it is appreciated.

**Comment by andreas-hofmann** [comment]
No worries mate - I've been there. ;) Just wanted to give something back, seems like there are not many converters for this purpose. Cheers!

**Comment by marcmerlin** [comment]
I had a quick look, as you could probably tell, this was random code I got from random places, plus my own fixes and code on top, and more cleanups/unifications could have been done, so thanks for doing them.
I'll restore the default size to 320x240 so that it matches the video capture size (linux code you probably aren't using but is in that same repo).

**Comment by marcmerlin** [comment]
I also tried your new ALGO 5 vs 3, and couldn't see a huge difference in my use case, but I'm fine with either.

**Pull request merged**
